-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- SISTEMA.....: AMADEUS CAPITALIZACAO
-- DESCRICAO...: AUTOMACAO DOS PROCESSOS DE ABATIMENTO DE EMPRESTIMO COM RESGATE DE COTAS NO REGIME PROGRESSIVO
-- ANALISTA....: ADRIANO LIMA
-- DATA CRIACAO: 08/09/2021
-- OBJETO......: OWN_FUNCESP.PRE_TRG_LOG_ABAT_EMPR
-- OBJETIVO....: GERAR O SEQUENCIA DA TABELA DA TABELA DE LOG DE FORMA AUTOMATIZADA
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SET ECHO ON
SET TIME ON
SET TIMING ON
SET SQLBL ON
SET SERVEROUTPUT ON SIZE 1000000
SET DEFINE OFF
SHOW USER
SELECT * FROM GLOBAL_NAME;
SELECT INSTANCE_NAME, HOST_NAME FROM V$INSTANCE;
SELECT TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS') DATA FROM DUAL;

CREATE OR REPLACE TRIGGER OWN_FUNCESP.PRE_TRG_LOG_STATUS
BEFORE INSERT ON OWN_FUNCESP.PRE_TBL_LOG_STATUS
FOR EACH ROW 
BEGIN
    IF :NEW.COD_LOG_STATUS IS NULL THEN
	
       SELECT OWN_FUNCESP.PRE_SEQ_LOG_STATUS.NEXTVAL INTO :NEW.COD_LOG_STATUS FROM DUAL;
    
    END IF;
END;
--
--
CREATE OR REPLACE TRIGGER OWN_FUNCESP.PRE_TRG_TBL_ETAPA
BEFORE INSERT ON OWN_FUNCESP.PRE_TBL_ETAPA
FOR EACH ROW 
BEGIN
    IF :NEW.COD_ETAPA IS NULL THEN
	
       SELECT OWN_FUNCESP.PRE_SEQ_TBL_ETAPA.NEXTVAL INTO :NEW.COD_ETAPA FROM DUAL;
    
    END IF;
END;
--
--
CREATE OR REPLACE TRIGGER OWN_FUNCESP.PRE_TRG_ABAT_EMP
BEFORE INSERT ON OWN_FUNCESP.PRE_TBL_LOG_PROCESSO_ABAT_EMP
FOR EACH ROW 
BEGIN
    IF :NEW.COD_LOG_ABAT IS NULL THEN
	
       SELECT OWN_FUNCESP.PRE_SEQ_ABAT_EMP.NEXTVAL INTO :NEW.COD_LOG_ABAT FROM DUAL;
    
    END IF;
END;
--
--
CREATE OR REPLACE TRIGGER OWN_FUNCESP.PRE_TRG_LOG_TRANSACAO_ABAT
BEFORE INSERT ON OWN_FUNCESP.PRE_TBL_LOG_TRANSACAO_ABAT_EMP
FOR EACH ROW 
BEGIN
    IF :NEW.COD_LOG_TRANS IS NULL THEN
	
       SELECT OWN_FUNCESP.PRE_SEQ_TRANSACAO_ABAT_EMP.NEXTVAL INTO :NEW.COD_LOG_TRANS FROM DUAL;
    
    END IF;
END;
