-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- SISTEMA.....: AMADEUS CAPITALIZACAO
-- DESCRICAO...: AUTOMACAO DOS PROCESSOS DE ABATIMENTO DE EMPRESTIMO COM RESGATE DE COTAS NO REGIME PROGRESSIVO
-- ANALISTA....: ADRIANO LIMA
-- DATA CRIACAO: 08/09/2021
-- OBJETO......: OWN_FUNCESP.PRE_TBL_LOG_ABAT_EMPR
-- OBJETIVO....: CRIACAO DE SINONIMO  
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SET ECHO ON
SET TIME ON
SET TIMING ON
SET SQLBL ON
SET SERVEROUTPUT ON SIZE 1000000
SET DEFINE OFF
SHOW USER
SELECT * FROM GLOBAL_NAME;
SELECT INSTANCE_NAME, HOST_NAME FROM V$INSTANCE;
SELECT TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS') DATA FROM DUAL;

CREATE SYNONYM SYS_FUNCESP.PRE_TBL_LOG_STATUS FOR OWN_FUNCESP.PRE_TBL_LOG_STATUS;
CREATE SYNONYM SYS_FUNCESP.PRE_TBL_ETAPA FOR OWN_FUNCESP.PRE_TBL_ETAPA;
CREATE SYNONYM SYS_FUNCESP.PRE_TBL_LOG_PROCESSO_ABAT_EMP FOR OWN_FUNCESP.PRE_TBL_LOG_PROCESSO_ABAT_EMP;
CREATE SYNONYM SYS_FUNCESP.PRE_TBL_LOG_TRANSACAO_ABAT_EMP FOR OWN_FUNCESP.PRE_TBL_LOG_TRANSACAO_ABAT_EMP;
--
CREATE SYNONYM SYS_FUNCESP.PRE_SEQ_LOG_STATUS FOR OWN_FUNCESP.PRE_SEQ_LOG_STATUS;
CREATE SYNONYM SYS_FUNCESP.PRE_SEQ_TBL_ETAPA FOR OWN_FUNCESP.PRE_SEQ_TBL_ETAPA;
CREATE SYNONYM SYS_FUNCESP.PRE_SEQ_ABAT_EMP FOR OWN_FUNCESP.PRE_SEQ_ABAT_EMP;
CREATE SYNONYM SYS_FUNCESP.PRE_SEQ_TRANSACAO_ABAT_EMP FOR OWN_FUNCESP.PRE_SEQ_TRANSACAO_ABAT_EMP;
