-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- SISTEMA.....: AMADEUS CAPITALIZACAO
-- DESCRICAO...: AUTOMACAO DOS PROCESSOS DE ABATIMENTO DE EMPRESTIMO COM RESGATE DE COTAS NO REGIME PROGRESSIVO
-- ANALISTA....: ADRIANO LIMA
-- DATA CRIACAO: 08/09/2021
-- OBJETO......: OWN_FUNCESP.PRE_TBL_LOG_STATUS/OWN_FUNCESP.PRE_TBL_LOG_TRANSACAO_ABAT_EMP
-- OBJETIVO....: POPULAR TABELAS DE CADASTRO
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SET ECHO ON
SET TIME ON
SET TIMING ON
SET SQLBL ON
SET SERVEROUTPUT ON SIZE 1000000
SET DEFINE OFF
SHOW USER
SELECT * FROM GLOBAL_NAME;
SELECT INSTANCE_NAME, HOST_NAME FROM V$INSTANCE;
SELECT TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS') DATA FROM DUAL;

INSERT INTO OWN_FUNCESP.PRE_TBL_LOG_STATUS (DCR_STATUS) VALUES ('PROCESSADO');
INSERT INTO OWN_FUNCESP.PRE_TBL_LOG_STATUS (DCR_STATUS) VALUES ('PENDENTE');
INSERT INTO OWN_FUNCESP.PRE_TBL_LOG_STATUS (DCR_STATUS) VALUES ('ERRO');
--
--
INSERT INTO OWN_FUNCESP.PRE_TBL_LOG_TRANSACAO_ABAT_EMP (DCR_ETAPA) VALUES ('CADASTRO');
INSERT INTO OWN_FUNCESP.PRE_TBL_LOG_TRANSACAO_ABAT_EMP (DCR_ETAPA) VALUES ('SIMUL_RESGATE');
INSERT INTO OWN_FUNCESP.PRE_TBL_LOG_TRANSACAO_ABAT_EMP (DCR_ETAPA) VALUES ('APUR_DESC_CONTAS');
INSERT INTO OWN_FUNCESP.PRE_TBL_LOG_TRANSACAO_ABAT_EMP (DCR_ETAPA) VALUES ('PROCESS_RESG_INDIV');
INSERT INTO OWN_FUNCESP.PRE_TBL_LOG_TRANSACAO_ABAT_EMP (DCR_ETAPA) VALUES ('CADASTRO_EFETIVADO');