-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- SISTEMA.....: AMADEUS CAPITALIZACAO
-- DESCRICAO...: AUTOMACAO DOS PROCESSOS DE ABATIMENTO DE EMPRESTIMO COM RESGATE DE COTAS NO REGIME PROGRESSIVO
-- ANALISTA....: ADRIANO LIMA
-- DATA CRIACAO: 08/09/2021
-- OBJETO......: OWN_FUNCESP.PRE_TBL_LOG_ABAT_EMPR
-- OBJETIVO....: CONCEDER PRIVILEGIO DE OPERACOES DML 
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SET ECHO ON
SET TIME ON
SET TIMING ON
SET SQLBL ON
SET SERVEROUTPUT ON SIZE 1000000
SET DEFINE OFF
SHOW USER
SELECT * FROM GLOBAL_NAME;
SELECT INSTANCE_NAME, HOST_NAME FROM V$INSTANCE;
SELECT TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS') DATA FROM DUAL;

GRANT SELECT ON OWN_FUNCESP.PRE_TBL_LOG_STATUS TO RFUNCESP_SELECT;
GRANT DELETE, INSERT, UPDATE ON OWN_FUNCESP.PRE_TBL_LOG_STATUS TO RFUNCESP_UPDATE;
--
GRANT SELECT ON OWN_FUNCESP.PRE_TBL_ETAPA TO RFUNCESP_SELECT;
GRANT DELETE, INSERT, UPDATE ON OWN_FUNCESP.PRE_TBL_ETAPA TO RFUNCESP_UPDATE;
--
GRANT SELECT ON OWN_FUNCESP.PRE_TBL_LOG_PROCESSO_ABAT_EMP TO RFUNCESP_SELECT;
GRANT DELETE, INSERT, UPDATE ON OWN_FUNCESP.PRE_TBL_LOG_PROCESSO_ABAT_EMP TO RFUNCESP_UPDATE;
--
GRANT SELECT ON OWN_FUNCESP.PRE_TBL_LOG_TRANSACAO_ABAT_EMP TO RFUNCESP_SELECT;
GRANT DELETE, INSERT, UPDATE ON OWN_FUNCESP.PRE_TBL_LOG_TRANSACAO_ABAT_EMP TO RFUNCESP_UPDATE;
--
GRANT SELECT ON OWN_FUNCESP.PRE_SEQ_LOG_STATUS TO RFUNCESP_SEQUENCE;  
GRANT SELECT ON OWN_FUNCESP.PRE_SEQ_TBL_ETAPA TO RFUNCESP_SEQUENCE; 
GRANT SELECT ON OWN_FUNCESP.PRE_SEQ_ABAT_EMP TO RFUNCESP_SEQUENCE; 
GRANT SELECT ON OWN_FUNCESP.PRE_SEQ_TRANSACAO_ABAT_EMP TO RFUNCESP_SEQUENCE;  
--
GRANT SELECT ON ATT.SIMULACAO_BENEF_FSS TO OWN_FUNCESP;
GRANT SELECT ON ATT.SIMULACAO_BENEF_CD_FSS TO OWN_FUNCESP;
GRANT SELECT ON ATT.SIMULACAO_FUNDO_FSS TO OWN_FUNCESP;
GRANT SELECT ON ATT.FCESP_TAB_VLR_ABAT_RESG TO OWN_FUNCESP;	
--
GRANT UPDATE ON OWN_FUNCESP.PRE_TBL_LOG_PROCESSO_ABAT_EMP TO ATT;



